# Generated by Django 4.2.3 on 2023-10-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_rename_rank_team_skill_remove_player_player_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=None),
        ),
    ]
