# Generated by Django 4.2.3 on 2023-10-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_team_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='level',
        ),
    ]
