# Generated by Django 4.2.3 on 2023-10-22 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_remove_team_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='skill',
            field=models.FloatField(default=-1),
        ),
    ]
