# Generated by Django 4.2.3 on 2023-10-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_alter_player_team_alter_team_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('weight', models.IntegerField(default=None)),
                ('cap', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='avgFB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='avgTD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
