# Generated by Django 4.2.3 on 2023-10-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_stat_player_assists_player_avgfb_player_avgtd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='scaledAssists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='scaledDeaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='scaledFB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='scaledGP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='scaledKills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='scaledLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='scaledTD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='scaledWins',
            field=models.IntegerField(default=0),
        ),
    ]
