# Generated by Django 4.2.3 on 2023-10-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_player_scaledassists_player_scaleddeaths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill',
            field=models.IntegerField(default=None),
        ),
    ]
