# Generated by Django 4.2.3 on 2023-10-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0009_player_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='assists',
            new_name='scaledKD',
        ),
        migrations.RemoveField(
            model_name='player',
            name='scaledAssists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='scaledDeaths',
        ),
        migrations.RemoveField(
            model_name='player',
            name='scaledKills',
        ),
    ]
