# Generated by Django 4.2.3 on 2023-10-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0011_rename_scaledlosses_player_scaledwr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='handle',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
