# Generated by Django 4.2.3 on 2023-10-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0012_alter_player_first_name_alter_player_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('skill', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='agedLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='agedWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ancientLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='ancientWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='avgPlayerSkill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='team',
            name='oldLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='oldWins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='scaledAgedWR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='scaledAncientLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='scaledLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='scaledOldWR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='scaledYoungWR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='totalPlayerSkill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='youngLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='youngWins',
            field=models.IntegerField(default=0),
        ),
    ]
