# Generated by Django 4.2.3 on 2023-10-23 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0013_region_team_agedlosses_team_agedwins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='scaledAncientLosses',
            new_name='scaledAncientWR',
        ),
    ]
