# Generated by Django 4.2.3 on 2023-10-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0014_rename_scaledancientlosses_team_scaledancientwr'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='scaledPlayerSkill',
            field=models.IntegerField(default=0),
        ),
    ]
