# Generated by Django 4.2.3 on 2023-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0015_team_scaledplayerskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='scaledAgedWR',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='scaledAncientWR',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='scaledLevel',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='scaledOldWR',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='scaledPlayerSkill',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='scaledYoungWR',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='skill',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
