# Generated by Django 4.2.3 on 2023-10-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0016_alter_team_scaledagedwr_alter_team_scaledancientwr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='scaledFB',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='scaledGP',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='scaledKD',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='scaledTD',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='scaledWR',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
