# Generated by Django 4.2.3 on 2023-10-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0017_alter_player_scaledfb_alter_player_scaledgp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.AddField(
            model_name='region',
            name='gamesPlayed',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='region',
            name='losses',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='region',
            name='scaledGamesPlayed',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='region',
            name='scaledWR',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='region',
            name='wins',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.region'),
        ),
    ]
